# Generated by Django 3.1 on 2020-12-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='thing',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
